//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Card_Delete {
            get {
                return ResourceManager.GetString("Card.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Card_Edit {
            get {
                return ResourceManager.GetString("Card.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Explorer.
        /// </summary>
        internal static string Card_OpenInExplorer {
            get {
                return ResourceManager.GetString("Card.OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Save File Directory.
        /// </summary>
        internal static string Card_OpenSaveFilePath {
            get {
                return ResourceManager.GetString("Card.OpenSaveFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Card_Run {
            get {
                return ResourceManager.GetString("Card.Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Backup.
        /// </summary>
        internal static string Card_SaveBackup {
            get {
                return ResourceManager.GetString("Card.SaveBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Save.
        /// </summary>
        internal static string Card_SaveManage {
            get {
                return ResourceManager.GetString("Card.SaveManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Restore.
        /// </summary>
        internal static string Card_SaveRestore {
            get {
                return ResourceManager.GetString("Card.SaveRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Guide.
        /// </summary>
        internal static string Card_SearchGuide {
            get {
                return ResourceManager.GetString("Card.SearchGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string Common_Backup {
            get {
                return ResourceManager.GetString("Common.Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Common_Delete {
            get {
                return ResourceManager.GetString("Common.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Common_Disabled {
            get {
                return ResourceManager.GetString("Common.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Sync.
        /// </summary>
        internal static string Common_DisableSync {
            get {
                return ResourceManager.GetString("Common.DisableSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Common_Enabled {
            get {
                return ResourceManager.GetString("Common.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sync.
        /// </summary>
        internal static string Common_EnableSync {
            get {
                return ResourceManager.GetString("Common.EnableSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch.
        /// </summary>
        internal static string Common_Fetch {
            get {
                return ResourceManager.GetString("Common.Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Common_Minutes {
            get {
                return ResourceManager.GetString("Common.Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Common_Restore {
            get {
                return ResourceManager.GetString("Common.Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Common_Running {
            get {
                return ResourceManager.GetString("Common.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Common_Start {
            get {
                return ResourceManager.GetString("Common.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Common_Unknown {
            get {
                return ResourceManager.GetString("Common.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URLs of screenshots, one per line.
        /// </summary>
        internal static string DetailPage_AddScreeshotsDialog_HelperText {
            get {
                return ResourceManager.GetString("DetailPage.AddScreeshotsDialog.HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Screenshots.
        /// </summary>
        internal static string DetailPage_AddScreeshotsDialog_Title {
            get {
                return ResourceManager.GetString("DetailPage.AddScreeshotsDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string DetailPage_Back {
            get {
                return ResourceManager.GetString("DetailPage.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string DetailPage_Character_Age {
            get {
                return ResourceManager.GetString("DetailPage.Character.Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string DetailPage_Character_Birthday {
            get {
                return ResourceManager.GetString("DetailPage.Character.Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Type.
        /// </summary>
        internal static string DetailPage_Character_BloodType {
            get {
                return ResourceManager.GetString("DetailPage.Character.BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string DetailPage_Character_Gender {
            get {
                return ResourceManager.GetString("DetailPage.Character.Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string DetailPage_Character_Information {
            get {
                return ResourceManager.GetString("DetailPage.Character.Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string DetailPage_Inforamtion_Tags {
            get {
                return ResourceManager.GetString("DetailPage.Inforamtion.Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Information.
        /// </summary>
        internal static string DetailPage_Information_GameInformation {
            get {
                return ResourceManager.GetString("DetailPage.Information.GameInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Introduction.
        /// </summary>
        internal static string DetailPage_Information_GameIntroduction {
            get {
                return ResourceManager.GetString("DetailPage.Information.GameIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string DetailPage_Information_Language {
            get {
                return ResourceManager.GetString("DetailPage.Information.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Sites.
        /// </summary>
        internal static string DetailPage_Information_RelatedSites {
            get {
                return ResourceManager.GetString("DetailPage.Information.RelatedSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        internal static string DetailPage_Information_ReleaseDate {
            get {
                return ResourceManager.GetString("DetailPage.Information.ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Releases.
        /// </summary>
        internal static string DetailPage_Information_Releases {
            get {
                return ResourceManager.GetString("DetailPage.Information.Releases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string DetailPage_Information_Staff {
            get {
                return ResourceManager.GetString("DetailPage.Information.Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Play Time.
        /// </summary>
        internal static string DetailPage_LastPlayTime {
            get {
                return ResourceManager.GetString("DetailPage.LastPlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Explorer.
        /// </summary>
        internal static string DetailPage_OpenInExplorer {
            get {
                return ResourceManager.GetString("DetailPage.OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Save File Directory.
        /// </summary>
        internal static string DetailPage_OpenSaveFilePath {
            get {
                return ResourceManager.GetString("DetailPage.OpenSaveFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Play Time.
        /// </summary>
        internal static string DetailPage_PlayTime {
            get {
                return ResourceManager.GetString("DetailPage.PlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add From Urls.
        /// </summary>
        internal static string DetailPage_Screenshots_AddFromUrl {
            get {
                return ResourceManager.GetString("DetailPage.Screenshots.AddFromUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set To Background.
        /// </summary>
        internal static string DetailPage_Screenshots_SetToBackground {
            get {
                return ResourceManager.GetString("DetailPage.Screenshots.SetToBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Guide.
        /// </summary>
        internal static string DetailPage_SearchGuide {
            get {
                return ResourceManager.GetString("DetailPage.SearchGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Than 1 mimutes.
        /// </summary>
        internal static string DetailPage_SmanllThanOneMinutes {
            get {
                return ResourceManager.GetString("DetailPage.SmanllThanOneMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string DetailPage_Staff_Artist {
            get {
                return ResourceManager.GetString("DetailPage.Staff.Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Design.
        /// </summary>
        internal static string DetailPage_Staff_CharacterDesign {
            get {
                return ResourceManager.GetString("DetailPage.Staff.CharacterDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string DetailPage_Staff_Director {
            get {
                return ResourceManager.GetString("DetailPage.Staff.Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string DetailPage_Staff_Music {
            get {
                return ResourceManager.GetString("DetailPage.Staff.Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        internal static string DetailPage_Staff_Scenario {
            get {
                return ResourceManager.GetString("DetailPage.Staff.Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        internal static string DetailPage_Staff_Song {
            get {
                return ResourceManager.GetString("DetailPage.Staff.Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string DetailPage_Staff_Staff {
            get {
                return ResourceManager.GetString("DetailPage.Staff.Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string DetailPage_Tab_Character {
            get {
                return ResourceManager.GetString("DetailPage.Tab.Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string DetailPage_Tab_Detail {
            get {
                return ResourceManager.GetString("DetailPage.Tab.Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Manage.
        /// </summary>
        internal static string DetailPage_Tab_SaveManage {
            get {
                return ResourceManager.GetString("DetailPage.Tab.SaveManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots.
        /// </summary>
        internal static string DetailPage_Tab_Screenshots {
            get {
                return ResourceManager.GetString("DetailPage.Tab.Screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Dialog_Button_Cancel {
            get {
                return ResourceManager.GetString("Dialog.Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Dialog_Button_Ok {
            get {
                return ResourceManager.GetString("Dialog.Button.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Dialog_Button_Save {
            get {
                return ResourceManager.GetString("Dialog.Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Dialog_Button_Upload {
            get {
                return ResourceManager.GetString("Dialog.Button.Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Dialog_Button_Yes {
            get {
                return ResourceManager.GetString("Dialog.Button.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Game Info.
        /// </summary>
        internal static string Dialog_Title_EditGameInfo {
            get {
                return ResourceManager.GetString("Dialog.Title.EditGameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tags, one per line.
        /// </summary>
        internal static string GameEditDialog_AddTagDialog_HelperText {
            get {
                return ResourceManager.GetString("GameEditDialog.AddTagDialog.HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tags.
        /// </summary>
        internal static string GameEditDialog_AddTagDialog_Title {
            get {
                return ResourceManager.GetString("GameEditDialog.AddTagDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string GameEditorDialog_Browse {
            get {
                return ResourceManager.GetString("GameEditorDialog.Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch.
        /// </summary>
        internal static string GameEditorDialog_Button_Fetch {
            get {
                return ResourceManager.GetString("GameEditorDialog.Button.Fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string GameEditorDialog_Caption_Desciption {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.Desciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string GameEditorDialog_Caption_Developer {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution File.
        /// </summary>
        internal static string GameEditorDialog_Caption_ExecutionFile {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.ExecutionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution File Path.
        /// </summary>
        internal static string GameEditorDialog_Caption_ExecutionFilePath {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.ExecutionFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name.
        /// </summary>
        internal static string GameEditorDialog_Caption_GameName {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Options:.
        /// </summary>
        internal static string GameEditorDialog_Caption_LaunchOptions {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.LaunchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        internal static string GameEditorDialog_Caption_ReleaseDate {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Cover.
        /// </summary>
        internal static string GameEditorDialog_ChangeCover {
            get {
                return ResourceManager.GetString("GameEditorDialog.ChangeCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LE Option.
        /// </summary>
        internal static string GameEditorDialog_LEOption {
            get {
                return ResourceManager.GetString("GameEditorDialog.LEOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunAsAdmin.
        /// </summary>
        internal static string GameEditorDialog_RunAsAdmin {
            get {
                return ResourceManager.GetString("GameEditorDialog.RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run with Sandboxie.
        /// </summary>
        internal static string GameEditorDialog_RunWithSandboxie {
            get {
                return ResourceManager.GetString("GameEditorDialog.RunWithSandboxie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run with VNGTTranslator.
        /// </summary>
        internal static string GameEditorDialog_RunWithVNGTTranslator {
            get {
                return ResourceManager.GetString("GameEditorDialog.RunWithVNGTTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File Path.
        /// </summary>
        internal static string GameEditorDialog_SavePath {
            get {
                return ResourceManager.GetString("GameEditorDialog.SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VNGTTranslator need amin.
        /// </summary>
        internal static string GameEditorDialog_VNGTTranslatorNeedAdmin {
            get {
                return ResourceManager.GetString("GameEditorDialog.VNGTTranslatorNeedAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPORT LOG.
        /// </summary>
        internal static string HelpPage_ExportLog {
            get {
                return ResourceManager.GetString("HelpPage.ExportLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Home_Add {
            get {
                return ResourceManager.GetString("Home.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add From Archive.
        /// </summary>
        internal static string Home_AddFromArchive {
            get {
                return ResourceManager.GetString("Home.AddFromArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add From Local.
        /// </summary>
        internal static string Home_AddFromLocal {
            get {
                return ResourceManager.GetString("Home.AddFromLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Home_AddGame {
            get {
                return ResourceManager.GetString("Home.AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Home_DeleteGame {
            get {
                return ResourceManager.GetString("Home.DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string Home_Filter_Developer {
            get {
                return ResourceManager.GetString("Home.Filter.Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXE Path.
        /// </summary>
        internal static string Home_Filter_ExePath {
            get {
                return ResourceManager.GetString("Home.Filter.ExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Home_Filter_GameName {
            get {
                return ResourceManager.GetString("Home.Filter.GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string Home_Filter_Tag {
            get {
                return ResourceManager.GetString("Home.Filter.Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Game.
        /// </summary>
        internal static string Home_InstallGame {
            get {
                return ResourceManager.GetString("Home.InstallGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Home_Refresh {
            get {
                return ResourceManager.GetString("Home.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Home_Search {
            get {
                return ResourceManager.GetString("Home.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Home_SelectAll {
            get {
                return ResourceManager.GetString("Home.SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection Mode.
        /// </summary>
        internal static string Home_SelectionMode {
            get {
                return ResourceManager.GetString("Home.SelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string Home_SortBy_Developer {
            get {
                return ResourceManager.GetString("Home.SortBy.Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        internal static string Home_SortBy_Favorite {
            get {
                return ResourceManager.GetString("Home_SortBy_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Home_SortBy_GameName {
            get {
                return ResourceManager.GetString("Home.SortBy.GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Played.
        /// </summary>
        internal static string Home_SortBy_LastPlayed {
            get {
                return ResourceManager.GetString("Home_SortBy_LastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Time.
        /// </summary>
        internal static string Home_SortBy_UploadTime {
            get {
                return ResourceManager.GetString("Home.SortBy.UploadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        internal static string Library_Button_AddFolder {
            get {
                return ResourceManager.GetString("Library.Button.AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selection.
        /// </summary>
        internal static string Library_Button_DeleteSelection {
            get {
                return ResourceManager.GetString("Library.Button.DeleteSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string Library_Button_Scan {
            get {
                return ResourceManager.GetString("Library.Button.Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Scan Complete.
        /// </summary>
        internal static string Library_ScanComplete {
            get {
                return ResourceManager.GetString("Library.ScanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Scan Start.
        /// </summary>
        internal static string Library_StartScan {
            get {
                return ResourceManager.GetString("Library.StartScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while detecting the game installation.
        /// </summary>
        internal static string Message_DetectGameInstallError {
            get {
                return ResourceManager.GetString("Message.DetectGameInstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist.
        /// </summary>
        internal static string Message_DirectoryNotExist {
            get {
                return ResourceManager.GetString("Message.DirectoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add game info.
        /// </summary>
        internal static string Message_FailedToAddGameInfo {
            get {
                return ResourceManager.GetString("Message.FailedToAddGameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add screenshots.
        /// </summary>
        internal static string Message_FailedToAddScreenshots {
            get {
                return ResourceManager.GetString("Message.FailedToAddScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove screenshots.
        /// </summary>
        internal static string Message_FailedToRemoveScreenshots {
            get {
                return ResourceManager.GetString("Message.FailedToRemoveScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update background image.
        /// </summary>
        internal static string Message_FailedToUpdateBackgroundImage {
            get {
                return ResourceManager.GetString("Message.FailedToUpdateBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale Emulator Not Found.
        /// </summary>
        internal static string Message_LENotFound {
            get {
                return ResourceManager.GetString("Message.LENotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No executable file can launch.
        /// </summary>
        internal static string Message_NoExecutionFile {
            get {
                return ResourceManager.GetString("Message.NoExecutionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Exist.
        /// </summary>
        internal static string Message_NotExist {
            get {
                return ResourceManager.GetString("Message.NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter doest not set.
        /// </summary>
        internal static string Message_ParameterNotSet {
            get {
                return ResourceManager.GetString("Message.ParameterNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please set execution file first.
        /// </summary>
        internal static string Message_PleaseSetExeFirst {
            get {
                return ResourceManager.GetString("Message.PleaseSetExeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related game not found.
        /// </summary>
        internal static string Message_RelatedGameNotFound {
            get {
                return ResourceManager.GetString("Message.RelatedGameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to decompress the archive.
        /// </summary>
        internal static string Message_UnableToDecompress {
            get {
                return ResourceManager.GetString("Message.UnableToDecompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update database failed.
        /// </summary>
        internal static string Message_UpdateDatabaseFailed {
            get {
                return ResourceManager.GetString("Message.UpdateDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Succeeded.
        /// </summary>
        internal static string Message_UpdateSuccess {
            get {
                return ResourceManager.GetString("Message.UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VNGTTranslator is not installed. Please go to the tools page to download it..
        /// </summary>
        internal static string Message_VNGTTranslatorNotInstalled {
            get {
                return ResourceManager.GetString("Message.VNGTTranslatorNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string Messeage_DeleteCheck {
            get {
                return ResourceManager.GetString("Messeage.DeleteCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string NavMenu_Game {
            get {
                return ResourceManager.GetString("NavMenu.Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string NavMenu_Help {
            get {
                return ResourceManager.GetString("NavMenu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string NavMenu_Library {
            get {
                return ResourceManager.GetString("NavMenu.Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string NavMenu_Setting {
            get {
                return ResourceManager.GetString("NavMenu.Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Set.
        /// </summary>
        internal static string NavMenu_TagSet {
            get {
                return ResourceManager.GetString("NavMenu.TagSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string NavMenu_Tools {
            get {
                return ResourceManager.GetString("NavMenu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto Fetch Info On Scan.
        /// </summary>
        internal static string Settings_Button_EnableAutoFetchInfoOnScan {
            get {
                return ResourceManager.GetString("Settings.Button.EnableAutoFetchInfoOnScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan From Installed.
        /// </summary>
        internal static string Settings_Button_ScanFromInstalled {
            get {
                return ResourceManager.GetString("Settings.Button.ScanFromInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Site.
        /// </summary>
        internal static string Settings_Caption_GuideSite {
            get {
                return ResourceManager.GetString("Settings.Caption.GuideSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language (Restart Needed).
        /// </summary>
        internal static string Settings_Caption_Language {
            get {
                return ResourceManager.GetString("Settings.Caption.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Settings_Caption_Setting {
            get {
                return ResourceManager.GetString("Settings.Caption.Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Mapping.
        /// </summary>
        internal static string Settings_Caption_TextMapping {
            get {
                return ResourceManager.GetString("Settings.Caption.TextMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Set.
        /// </summary>
        internal static string TagSetPage_Title {
            get {
                return ResourceManager.GetString("TagSetPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string ToolsPage_Builtin {
            get {
                return ResourceManager.GetString("ToolsPage.Builtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string ToolsPage_Custom {
            get {
                return ResourceManager.GetString("ToolsPage.Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tools Folder.
        /// </summary>
        internal static string ToolsPage_OpenToolsFolder {
            get {
                return ResourceManager.GetString("ToolsPage.OpenToolsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string ToolsPage_Title {
            get {
                return ResourceManager.GetString("ToolsPage.Title", resourceCulture);
            }
        }
    }
}
