//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameManager.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        internal static string Card_Delete {
            get {
                return ResourceManager.GetString("Card.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        internal static string Card_Edit {
            get {
                return ResourceManager.GetString("Card.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open in Explorer 的當地語系化字串。
        /// </summary>
        internal static string Card_OpenInExplorer {
            get {
                return ResourceManager.GetString("Card.OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Run 的當地語系化字串。
        /// </summary>
        internal static string Card_Run {
            get {
                return ResourceManager.GetString("Card.Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        internal static string Dialog_Button_Cancel {
            get {
                return ResourceManager.GetString("Dialog.Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        internal static string Dialog_Button_Ok {
            get {
                return ResourceManager.GetString("Dialog.Button.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save 的當地語系化字串。
        /// </summary>
        internal static string Dialog_Button_Save {
            get {
                return ResourceManager.GetString("Dialog.Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload 的當地語系化字串。
        /// </summary>
        internal static string Dialog_Button_Upload {
            get {
                return ResourceManager.GetString("Dialog.Button.Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Yes 的當地語系化字串。
        /// </summary>
        internal static string Dialog_Button_Yes {
            get {
                return ResourceManager.GetString("Dialog.Button.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit Game Info 的當地語系化字串。
        /// </summary>
        internal static string Dialog_Title_EditGameInfo {
            get {
                return ResourceManager.GetString("Dialog.Title.EditGameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Description 的當地語系化字串。
        /// </summary>
        internal static string GameEditorDialog_Caption_Desciption {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.Desciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Developer 的當地語系化字串。
        /// </summary>
        internal static string GameEditorDialog_Caption_Developer {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Execution File 的當地語系化字串。
        /// </summary>
        internal static string GameEditorDialog_Caption_ExecutionFile {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.ExecutionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Execution File Path 的當地語系化字串。
        /// </summary>
        internal static string GameEditorDialog_Caption_ExecutionFilePath {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.ExecutionFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Game Name 的當地語系化字串。
        /// </summary>
        internal static string GameEditorDialog_Caption_GameName {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Launch Options: 的當地語系化字串。
        /// </summary>
        internal static string GameEditorDialog_Caption_LaunchOptions {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.LaunchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Release Date 的當地語系化字串。
        /// </summary>
        internal static string GameEditorDialog_Caption_ReleaseDate {
            get {
                return ResourceManager.GetString("GameEditorDialog.Caption.ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change Cover 的當地語系化字串。
        /// </summary>
        internal static string GameEditorDialog_ChangeCover {
            get {
                return ResourceManager.GetString("GameEditorDialog.ChangeCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LE Option 的當地語系化字串。
        /// </summary>
        internal static string GameEditorDialog_LEOption {
            get {
                return ResourceManager.GetString("GameEditorDialog.LEOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RunAsAdmin 的當地語系化字串。
        /// </summary>
        internal static string GameEditorDialog_RunAsAdmin {
            get {
                return ResourceManager.GetString("GameEditorDialog.RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add 的當地語系化字串。
        /// </summary>
        internal static string Home_AddGame {
            get {
                return ResourceManager.GetString("Home.AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        internal static string Home_DeleteGame {
            get {
                return ResourceManager.GetString("Home.DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Developer 的當地語系化字串。
        /// </summary>
        internal static string Home_Filter_Developer {
            get {
                return ResourceManager.GetString("Home.Filter.Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EXE Path 的當地語系化字串。
        /// </summary>
        internal static string Home_Filter_ExePath {
            get {
                return ResourceManager.GetString("Home.Filter.ExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        internal static string Home_Filter_GameName {
            get {
                return ResourceManager.GetString("Home.Filter.GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Refresh 的當地語系化字串。
        /// </summary>
        internal static string Home_Refresh {
            get {
                return ResourceManager.GetString("Home.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select All 的當地語系化字串。
        /// </summary>
        internal static string Home_SelectAll {
            get {
                return ResourceManager.GetString("Home.SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Selection Mode 的當地語系化字串。
        /// </summary>
        internal static string Home_SelectionMode {
            get {
                return ResourceManager.GetString("Home.SelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Developer 的當地語系化字串。
        /// </summary>
        internal static string Home_SortBy_Developer {
            get {
                return ResourceManager.GetString("Home.SortBy.Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Favorite 的當地語系化字串。
        /// </summary>
        internal static string Home_SortBy_Favorite {
            get {
                return ResourceManager.GetString("Home_SortBy_Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        internal static string Home_SortBy_GameName {
            get {
                return ResourceManager.GetString("Home.SortBy.GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Last Played 的當地語系化字串。
        /// </summary>
        internal static string Home_SortBy_LastPlayed {
            get {
                return ResourceManager.GetString("Home_SortBy_LastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload Time 的當地語系化字串。
        /// </summary>
        internal static string Home_SortBy_UploadTime {
            get {
                return ResourceManager.GetString("Home.SortBy.UploadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add Folder 的當地語系化字串。
        /// </summary>
        internal static string Library_Button_AddFolder {
            get {
                return ResourceManager.GetString("Library.Button.AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete Selection 的當地語系化字串。
        /// </summary>
        internal static string Library_Button_DeleteSelection {
            get {
                return ResourceManager.GetString("Library.Button.DeleteSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scan 的當地語系化字串。
        /// </summary>
        internal static string Library_Button_Scan {
            get {
                return ResourceManager.GetString("Library.Button.Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Locale Emulator Not Found 的當地語系化字串。
        /// </summary>
        internal static string Message_LENotFound {
            get {
                return ResourceManager.GetString("Message.LENotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No executable file can launch 的當地語系化字串。
        /// </summary>
        internal static string Message_NoExecutionFile {
            get {
                return ResourceManager.GetString("Message.NoExecutionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not Exist 的當地語系化字串。
        /// </summary>
        internal static string Message_NotExist {
            get {
                return ResourceManager.GetString("Message.NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 please set execution file first 的當地語系化字串。
        /// </summary>
        internal static string Message_PleaseSetExeFirst {
            get {
                return ResourceManager.GetString("Message.PleaseSetExeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Related game not found 的當地語系化字串。
        /// </summary>
        internal static string Message_RelatedGameNotFound {
            get {
                return ResourceManager.GetString("Message.RelatedGameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update Succeeded 的當地語系化字串。
        /// </summary>
        internal static string Message_UpdateSuccess {
            get {
                return ResourceManager.GetString("Message.UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Game 的當地語系化字串。
        /// </summary>
        internal static string NavMenu_Game {
            get {
                return ResourceManager.GetString("NavMenu.Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Library 的當地語系化字串。
        /// </summary>
        internal static string NavMenu_Library {
            get {
                return ResourceManager.GetString("NavMenu.Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings 的當地語系化字串。
        /// </summary>
        internal static string NavMenu_Setting {
            get {
                return ResourceManager.GetString("NavMenu.Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable Auto Fetch Info On Scan 的當地語系化字串。
        /// </summary>
        internal static string Settings_Button_EnableAutoFetchInfoOnScan {
            get {
                return ResourceManager.GetString("Settings.Button.EnableAutoFetchInfoOnScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scan From Installed 的當地語系化字串。
        /// </summary>
        internal static string Settings_Button_ScanFromInstalled {
            get {
                return ResourceManager.GetString("Settings.Button.ScanFromInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language (Restart Needed) 的當地語系化字串。
        /// </summary>
        internal static string Settings_Caption_Language {
            get {
                return ResourceManager.GetString("Settings.Caption.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting 的當地語系化字串。
        /// </summary>
        internal static string Settings_Caption_Setting {
            get {
                return ResourceManager.GetString("Settings.Caption.Setting", resourceCulture);
            }
        }
    }
}
